accounts/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo, Length, Regexp, Email



class RegistrationForm(FlaskForm):
    email = StringField(validators=[DataRequired(), Email(message= 'Invalid Email.')])
    firstname = StringField(validators=[DataRequired(), Regexp(regex = '^[A-Za-z-]+$', message= 'Name must only include English letters and/or hyphens (-)')])
    lastname = StringField(validators=[DataRequired(), Regexp(regex = '^[A-Za-z-]+$', message= 'Name must only include English letters and/or hyphens (-))')])
    phone = StringField(validators=[DataRequired(), Regexp(regex = '^(02\d-\d{8}|011\d-\d{7}|01\d{2,3}-\d{5,6})$', message='Invalid phone number')])
    password = PasswordField(validators=[DataRequired(), Length(min = 8, message = "Length of password must be longer than 8."), Regexp(regex ='^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*\W)[a-zA-Z\d\W]', message = "Invalid password. Valid password must contain: \nAtleast one special character\nAtleast one uppercase character\nAtleast 8 characters in total")])
    confirm_password = PasswordField(validators=[DataRequired(), EqualTo('password', message="Both password fields must be the same.")])
    submit = SubmitField()

class LoginForm(FlaskForm):
    email = StringField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])
    mfa_pin = StringField(validators=[DataRequired()])
    #recaptcha = RecaptchaField()
    submit = SubmitField()

accounts/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, request, get_flashed_messages
from accounts.forms import RegistrationForm, LoginForm
from flask_login import login_user, current_user, login_required, logout_user
from markupsafe import Markup
from utils import Sym_Encryption

import argon2
import pyotp
import re
import logging

from config import Config
from models import User



accounts_bp = Blueprint('accounts', __name__, template_folder='templates')
logger = logging.getLogger('logger')


@accounts_bp.route('/account')
@login_required
def account():

    user_posts = Sym_Encryption.decrypt_all_posts(current_user.posts)


    if current_user:
        return render_template("accounts/account.html", posts = user_posts, user = current_user)

@accounts_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

@accounts_bp.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    #session authentication limit


    if current_user.is_authenticated:
        flash("You are already logged in.", category='info')
        return redirect(url_for('posts.posts'))

    ##if no attempts in session (new session)
    if session.get('attempts') is None:
        #clear falshed messages
        session['attempts'] = 0

    
    #if session attempts exceeded
    if session['attempts'] > Config.MAX_LOGIN_ATTEMPTS:
        reset_link = url_for('accounts.unlock')
        message = Markup(f'You have exceeded the maximum login attempts. <a href="{reset_link}">Click here to reset your attempts</a>.')
        flash(message, category='danger')
        logger.warning(f"[User:{form.email.data}, Attempts:{session['attempts']}, IP:{request.remote_addr}] Maximum login attempts reached.")
        return render_template('accounts/login.html')



    # On submit login form.
    if form.validate_on_submit():
        #user not real
        if not User.check_user_is_real(form.email.data):
            rem = handle_invalid_login_session(form.email.data)
            flash(f'Cannot find user email. {rem} attemp(s) remaining.', category='warning')
            return render_template('accounts/login.html', form = form)

        #password does not match
        if not User.verify_password_against_email(form.email.data, form.password.data):
            rem = handle_invalid_login_session(form.email.data)
            flash(f'Incorrect password. {rem} attemp(s) remaining.', category='warning')
            return render_template('accounts/login.html', form = form)


        user = User.find_user_from_email(form.email.data)
        pin_correct = user.verify_mfa_pin(input_pin = form.mfa_pin.data)
        mfa_enabled = user.verify_mfa_enabled()

        ##correct login+2fa
        if pin_correct:
            #reset attempts
            session.pop('attempts', None)
            #if MFa not enabled, set to true of successful login.
            if not user.verify_mfa_enabled():
                user.update_mfa(True)

            login_user(user)
            flash(f'Logged in.', category='success')
            
            #Generate log
            user.generate_log()

            #Check user privilegedes
            if current_user.role == 'db_admin':
                return redirect('http://127.0.0.1:5000/admin')
            elif current_user.role == 'sec_admin':
                return redirect(url_for('security.security'))
        
            return redirect(url_for('posts.posts'))
        ##
        ##
        ##Incorrect login attempt        

        #Incorrect pin entered and MFa not setup
        if not mfa_enabled and not pin_correct:
            flash('You have not enabled Multi-Factor Authentication. Please enable first to login.', category='error')
            qrURI = str(pyotp.totp.TOTP(user.mfa_key).provisioning_uri(form.email.data, 'CSC2035 BLOG'))
            return render_template('accounts/setup_mfa.html', secret=user.mfa_key, URI = qrURI)

        #if mfa setup and pin incorrect
        if mfa_enabled and not pin_correct: #pin correct check redundant but added for readability
            flash(f'Incorrect pin entered. {rem} attemp(s) remaining.', category='warning')
            return render_template('accounts/login.html', form = form)

    
    return render_template('accounts/login.html', form = form)

@accounts_bp.route('/unlock')
def unlock():
    session.pop('attempts', None)
    if '_flashes' in session:
        session['_flashes'].clear() #removed flashed messages
    flash('Login attempts have been reset. You can try logging in again.', category='success')
    return redirect(url_for('accounts.login'))

@accounts_bp.route('/registration', methods=['GET','POST'])
def registration():

    form = RegistrationForm()

    if current_user.is_authenticated:
        flash("You are already logged in.", category='info')
        return redirect(url_for('posts.posts'))

    if form.validate_on_submit():

        #Check if email alreaady exists
        if User.check_user_is_real(form.email.data):
            flash('Email already exists. ', category="danger")
            return render_template('accounts/registration.html', form=form)

        #create and commite new users
        new_user = User.create_user(form.email.data, form.firstname.data, form.lastname.data, form.phone.data, form.password.data)
        
        if new_user:
            flash('Account Created. You must set up Multi-Factor Authentication to login.', category='success')
            qrURI = str(pyotp.totp.TOTP(new_user.mfa_key).provisioning_uri(form.email.data, 'CSC2035 BLOG'))
            return render_template('accounts/setup_mfa.html', secret=new_user.mfa_key, URI = qrURI)

    return render_template('accounts/registration.html', form=form)



def handle_invalid_login_session(email):
    session['attempts'] += 1
    logger.warning(f"[User:{email}, Attempts:{session['attempts']}, IP:{request.remote_addr}] Invalid login.")
    return (Config.MAX_LOGIN_ATTEMPTS - session['attempts'])

posts/views.py
from flask import Blueprint, render_template, flash, url_for, redirect
from flask_login import current_user,login_required
from posts.forms import PostForm


from utils import roles_required, Sym_Encryption
from models import Post

from sqlalchemy import desc



posts_bp = Blueprint('posts', __name__, template_folder='templates')


@posts_bp.route('/create/', methods=('GET', 'POST'))
@login_required
@roles_required('end_user')
def create():
    form = PostForm()

    if form.validate_on_submit():
        Post.create_post(current_user,form.title.data,form.body.data)

        flash('Post created', category='success')
        return redirect(url_for('posts.posts'))

    return render_template('posts/create.html', form=form)
    
@posts_bp.route('/posts')
@login_required
@roles_required('end_user')
def posts():

    all_posts = Sym_Encryption.decrypt_all_posts(Post.get_all_posts())
    return render_template('posts/posts.html', posts=all_posts)

@posts_bp.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
@roles_required('end_user')
def update(id):


    if check_current_user_created_post(id):
        post_to_update = Sym_Encryption.decrypt_post(Post.get_post(id))

        if not post_to_update:
            flash('Post not found.', category='warning')
            return redirect(url_for('posts.posts'))

        form = PostForm()

        if form.validate_on_submit():
            new_title = Sym_Encryption.encrypt_text(current_user, form.title.data)
            new_body = Sym_Encryption.encrypt_text(current_user, form.body.data)
            
            post_to_update.update(title=new_title, body=new_body)
            flash('Post updated', category='success')
            return redirect(url_for('posts.posts'))


        form.title.data = post_to_update.title
        form.body.data = post_to_update.body

        return render_template('posts/update.html', form=form)
    else:
        flash('You did not post this post.', category='warning')
        return redirect(url_for('posts.posts'))

@posts_bp.route('/<int:id>/delete')
@login_required
@roles_required('end_user')
def delete(id):




    if check_current_user_created_post(id):
        Post.delete(id)

        flash('Post deleted', category='success')
        return redirect(url_for('posts.posts'))
    else:
        flash('You did not post this post.', category='warning')
        return redirect(url_for('posts.posts'))
    

def check_current_user_created_post(id):
    return current_user.id == Post.query.filter_by(id=id).first().userid

templates/accounts/account.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Account</h1>
    <div class="p-2 row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="p-2 bg-light border border-primary" style="text-align: left">
                <div>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                onclick=delete_flash(this)>
                            <span>&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endwith %}
                </div>
                    <div class="card border border-dark">
                        <div class="card-header card-body border border-dark">
                            <label><b>Account no:</b></label><p> {{ user.id }} </p>
                            <label><b>Email:</b></label> <p> {{ user.emaik }} </p>
                            <label><b>First name:</b></label> <p> {{ user.firstname }} </p>
                            <label><b>Last name:</b></label> <p> {{ user.lastname }} </p>
                            <label><b>Phone:</b></label> <p> {{ user.phone }} </p>
                            <label><b>Posts:</b></label>
                            {% for post in posts %}
                            <div class="card border border-dark">
                                <div class="card-header bg-dark text-white border border-dark">
                                    <h4>{{ post.title }}</h4>
                                    <small>Author:{{ post.user.firstname }} {{ post.user.lastname }}</small>
                                    <small>{{ post.created.strftime('%H:%M:%S %d-%m-%Y') }}</small>
                                </div>
                                <div class="card-body">{{ post.body }}</div>
        
        
                                <div class="card-footer">
                                    <a class="navbar-item" href="{{ url_for('posts.update', id=post.id) }}">Update</a>
                                    <a class="navbar-item" href="{{ url_for('posts.delete', id=post.id) }}">Delete</a>
                                </div>
                                </div>
                            <br>
                            {% endfor %}
                        </div>



                    </div>
                    <br>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <div class="p-2 row">
        <div class="col-3"></div>
        <div class="col-6">
            {%if form%}
            <form method="POST">
                <div class="p-3 bg-light border border-primary">
                    <div style="text-align: left">
                        {{ form.csrf_token() }}
                        <div>
                            {% with messages = get_flashed_messages(with_categories=true) %}
                            {% for category, message in messages %}
                            <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        onclick=delete_flash(this)>
                                    <span>&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                            {% endwith %}
                        </div>
                        
                        <div class="form-group">
                            {{ form.email.label}}<span style="color: red">*</span>
                            {{ form.email(class="form-control") }}
                        </div>

                        <div class="form-group">
                            {{ form.password.label}}<span style="color: red">*</span>
                            {{ form.password(class="form-control") }}
                        </div>

                        <div class="form-group">
                            {{ form.mfa_pin.label}}<span style="color: red">*</span>
                            {{ form.mfa_pin(class="form-control") }}
                        </div>

                        </div>
                        <div>
                            {{ form.recaptcha }}
                        </div>
                        <div>                     
                            {{ form.submit(class="btn btn-success") }}
                        </div>
                    
                </div>
            </form>

            {% else %}
            <div class="alert alert-danger mt-3">
                You have exceeded the maximum login attempts. 
                <a href="{{ url_for('accounts.unlock') }}" class="alert-link">Click here to reset your attempts</a>.
            </div>
            {% endif %}

        </div>
        <div class="col-3"></div>
    </div>

</div>
{% endblock %}

templates/accounts/registration.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Registration</h1>
    <div class="p-2 row">
        <div class="col-3"></div>
        <div class="col-6">
            <div>
                <p>Please complete the following form to register an account to use the CSC2031 Blog.</p>
            </div>

            <form method="POST">
                <div class="p-2 bg-light border border-primary">
                    <div style="text-align: left">
                        {{ form.csrf_token() }}
                        <div>
                            {% with messages = get_flashed_messages(with_categories=true) %}
                                {% for category, message in messages %}
                                    <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                                        {{ message }}.
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" onclick="delete_flash(this)">
                                            <span>&times;</span>
                                        </button>
                                    </div>
                                {% endfor %}
                            {% endwith %}
                        </div>

                        <div class="form-group">
                            {{ form.email.label}}<span style="color: red">*</span>
                            {{ form.email(class="form-control") }}
                            {% if form.email.errors %}
                                <ul class="text-danger">
                                    {% for error in form.email.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            {{ form.firstname.label}}<span style="color: red">*</span>
                            {{ form.firstname(class="form-control") }}
                            {% if form.firstname.errors %}
                                <ul class="text-danger">
                                    {% for error in form.firstname.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        
                        <div class="form-group">
                            {{ form.lastname.label}}<span style="color: red">*</span>
                            {{ form.lastname(class="form-control") }}
                            {% if form.lastname.errors %}
                                <ul class="text-danger">
                                    {% for error in form.lastname.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            {{ form.phone.label}}<span style="color: red">*</span>
                            {{ form.phone(class="form-control") }}
                            {% if form.phone.errors %}
                                <ul class="text-danger">
                                    {% for error in form.phone.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            {{ form.password.label}}<span style="color: red">*</span>
                            {{ form.password(class="form-control") }}
                            {% if form.password.errors %}
                                <ul class="text-danger">
                                    {% for error in form.password.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            {{ form.confirm_password.label}}<span style="color: red">*</span>
                            {{ form.confirm_password(class="form-control") }}
                            {% if form.confirm_password.errors %}
                                <ul class="text-danger">
                                    {% for error in form.confirm_password.errors %}
                                        <li><p>{{ error }}</p></li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                    <div>
                        {{ form.submit(class="btn btn-success") }}
                    </div>
                </div>
            </form>

        </div>
        <div class="col-3"></div>
    </div>

</div>
{% endblock %}

templates/accounts/setup_mfa.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Setup MFA for this account.</h1>
    <div class="col-3"></div>
    <div class="col-6">
        <div class="p-2 row">
            <div class="p-2 bg-light border border-primary">
                <div style="text-align: left">

                    <div>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                        {% for category, message in messages %}
                        <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    onclick=delete_flash(this)>
                                <span>&times;</span>
                            </button>
                        </div>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                <div class="p-2">
                    Open Miscrosoft Authenticator on phone, or use signup through there.
                </div>
                <div class="p-2">
                    Alternatively use Google Authenticator
                </div>
                <div class="p-2">
                    Select new account and enter code below:
                </div>
                <div class="p-2 bg-light border border-primary">
                    <h2>CODE</h2>
                    {{ secret }}
                    <h2>QR</h2>
                    <img src="{{ qrcode(URI, box_size=5, border=5) }}"">
                </div>
                <div>
                    Once completed, please click <a href="{{ url_for('accounts.login') }}">here</a> to login.
                </div>
            </div>
        </div>
        </div>
</div>
{% endblock %}